{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arthenica",
    "module": "ffmpeg-kit-min",
    "version": "6.0-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.arthenica",
          "module": "smart-exception-java",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-kit-min-6.0-2.aar",
          "url": "ffmpeg-kit-min-6.0-2.aar",
          "size": 28528648,
          "sha512": "3ac4dc62bb1ae7c25a92ad575003bd365c2fb467bee37e1967a005dd0004867d55c31b6e76690b56fb55be70e4cacf82285e1a20bf541193bb945133e1feee3b",
          "sha256": "3a60ef6fecd48b5f1c91396ae942b0edd138324503ce7962d7c8bada3cbfba13",
          "sha1": "65732abe889138a5fe1f634080432ca407b5ff90",
          "md5": "90f0b14f922aa3a8b818a1d99a541580"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.arthenica",
          "module": "smart-exception-java",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-kit-min-6.0-2.aar",
          "url": "ffmpeg-kit-min-6.0-2.aar",
          "size": 28528648,
          "sha512": "3ac4dc62bb1ae7c25a92ad575003bd365c2fb467bee37e1967a005dd0004867d55c31b6e76690b56fb55be70e4cacf82285e1a20bf541193bb945133e1feee3b",
          "sha256": "3a60ef6fecd48b5f1c91396ae942b0edd138324503ce7962d7c8bada3cbfba13",
          "sha1": "65732abe889138a5fe1f634080432ca407b5ff90",
          "md5": "90f0b14f922aa3a8b818a1d99a541580"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ffmpeg-kit-min-6.0-2-sources.jar",
          "url": "ffmpeg-kit-min-6.0-2-sources.jar",
          "size": 52797,
          "sha512": "e2b5124008aa5438c3477ae1d1f5b1e9d3b0f13f513e1b6d458c3ec5d25a52400a5abd5bc1535929bfff042625a7ebd4281fc3f93e95261f6a55dfe0b28993cb",
          "sha256": "0a3a53d0bb9fa75341c610fefc54590e99f735e60d56916a3509ac3051ac3b00",
          "sha1": "767e676594e638b42e22aceedce743da8eab9a3f",
          "md5": "a866d207fad8b7ceb28e5d46d407189d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ffmpeg-kit-min-6.0-2-javadoc.jar",
          "url": "ffmpeg-kit-min-6.0-2-javadoc.jar",
          "size": 415302,
          "sha512": "f4380d8a1a36f42b054b6223a86995b1508e5c38077dd6142e7134b83b3c24347a649696d9a991d63092ea1ff713f7131473e0a8d9fd29a8f3a2062da4551e88",
          "sha256": "4a7ce00445a9229e9c3f19dadc3f39676ef37608fee9bd97a46dc84fb8406c17",
          "sha1": "8844f188e3f239cea8c3fb1356bf03913cec6ac6",
          "md5": "f1d736e9ef1484c8a0c58db5e559fb17"
        }
      ]
    }
  ]
}
